added shopping cart and cart items functional
luk14n/book-store pull request #13
Opened 2024-02-26 15:44 UTC by luk14n

2024-02-26 20:04 UTC, kerrrusha requested changes

2024-02-26 20:04 UTC, kerrrusha commented on src/main/java/com/lukian/bookstore/service/cart/ShoppingCartServiceImpl.java
> +        ShoppingCart cartFromDB = getCartFromDB(userId);
if cart is not found we should create a new one, not throw exception

2024-02-26 20:04 UTC, kerrrusha commented on src/main/java/com/lukian/bookstore/service/cart/ShoppingCartServiceImpl.java
> +        CartItem requestedItemToAdd = itemMapper.toModel(requestDto);
book is not added, get it by id from DB and set properly

2024-02-27 11:52 UTC, Vasul-Pankiv requested changes

2024-02-27 11:52 UTC, Vasul-Pankiv commented on src/main/java/com/lukian/bookstore/service/cart/ShoppingCartServiceImpl.java
> +        return cartFromDb.get();
you can simplify it. Find the users first and then use orElseGet() to get or create shopping cart

2024-02-28 10:11 UTC, Rommelua commented on src/main/java/com/lukian/bookstore/model/ShoppingCart.java
> +public class ShoppingCart {
Don't forget to implement soft delete approach

2024-02-28 10:11 UTC, Rommelua commented on src/main/java/com/lukian/bookstore/service/cart/ShoppingCartServiceImpl.java
> +    private final ShoppingCartMapper cartMapper;
```suggestion
    private final CartItemMapper itemMapper;
    private final ShoppingCartMapper cartMapper;
```

2024-02-28 10:11 UTC, Rommelua commented on src/main/java/com/lukian/bookstore/service/user/UserServiceImpl.java
> +        user.setRoles(roles);
```suggestion
```

2024-02-28 11:45 UTC, kozhukhovsky approved these changes

2024-02-28 12:19 UTC, merged